---
- hosts: web_servers
  become: true
  tasks:
  #pre_tasks Do before tasks

    - name: Update repository index on Debian family OS
      tags: always
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update repository index on Redhat family OS
      tags: always
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install Apache web server && Apache
      tags: apache, php
      package:
        name: 
        - "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        - "{{ 'libapache2-mod-php' if ansible_os_family == 'Debian' else 'php' }}"
        state: latest