---
- hosts: web_servers
  become: true
  tasks:
  #pre_tasks Do before tasks

    - name: Update repository index on Debian family OS
      tags: always
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update repository index on Redhat family OS
      tags: always
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"

#Install package example
    - name: Install Apache web server && Apache
      tags: apache, php
      package:
        name: 
        - "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        - "{{ 'libapache2-mod-php' if ansible_os_family == 'Debian' else 'php' }}"
        state: latest

#Service example
    - name: start httpd (Centos)
      tags: apache, redhat, httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

#Copy file example
    - name: copy default htlm file for site #ansible-playbook --ask-become-pass install_apache.yml --tags copy_file
      tags: apache, copy_file
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root 
        group: root 
        mode: 0644
    
#Manipulate text example
    - name: change e-mail addressx for admin
      tags: email 
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_os_family == "RedHat"
      register: httpd

#Auto restart httpd when above file is changed
    - name: restart httpd (Centos)
      tags: apache,centos,httpd
      service:
        name: httpd
        state: restarted 
      when: httpd.changed
      

#Install from url example
- hosts: workstations 
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      destination: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root